2025-04-04 23:27:11 - INFO - resume_analyzer - logging_setup.py:71 - Log file created at logs\resume_analyzer_20250404_232711.log
2025-04-04 23:27:11 - INFO - resume_analyzer - logging_setup.py:73 - Logging initialized at level INFO
2025-04-04 23:27:38 - ERROR - resume_analyzer.core.llm_client - llm_client.py:53 - Error during request: 'text'
2025-04-04 23:27:38 - INFO - resume_analyzer.core.llm_client - llm_client.py:55 - Retrying in 2 seconds...
2025-04-04 23:27:45 - ERROR - resume_analyzer.core.llm_client - llm_client.py:53 - Error during request: 'text'
2025-04-04 23:27:45 - INFO - resume_analyzer.core.llm_client - llm_client.py:55 - Retrying in 2 seconds...
2025-04-04 23:27:52 - ERROR - resume_analyzer.core.llm_client - llm_client.py:53 - Error during request: 'text'
2025-04-04 23:28:07 - INFO - resume_analyzer.__main__ - main.py:97 - Running both API and UI
